2023-08-09 release
odradev/awesome-zero-knowledge pull request #24
Opened 2023-08-08 14:01 UTC by aleksanderziel

2023-08-09 release

2023-08-09 10:22 UTC, zie1ony requested changes
Add all the whitepapers and articles I mentioned as TopPicks to README.md

2023-08-09 10:22 UTC, zie1ony commented on newsletters/2023-08-09-newsletter.md
> +* [Resolving a Cairo 2 error building a Smart Contract : “internal error: entered unreachable code”](https://medium.com/@elielmathe/resolving-a-puzzling-cairo-2-syntax-error-in-smart-contracts-a70368
This is not interesting. Remove it.

2023-08-09 10:22 UTC, zie1ony commented on newsletters/2023-08-09-newsletter.md
> +* [A Primer for the Zero-Knowledge Cryptography: Part I](https://medium.com/@rabiafatima/a-primer-for-the-zero-knowledge-cryptography-part-i-85b5d5190aef) - article by Rabia Fatima. (06.08.2023)
Top Pick

2023-08-09 10:22 UTC, zie1ony commented on newsletters/2023-08-09-newsletter.md
> +* [Scaling Ethereum with zkRollups: Empowering the Future of Blockchain Technology](https://www.deadlinenews.co.uk/2023/08/07/scaling-ethereum-with-zkrollups-empowering-the-future-of-blockchain-techn
Remove it.

2023-08-09 10:22 UTC, zie1ony commented on newsletters/2023-08-09-newsletter.md
> +* [Endgame: Proof of Governance](https://dba.mirror.xyz/UTPfxWe65dYrUu_RJX-5VkAJypFRyw3AZh6m0dRXYZk) - article by Jon Charbonneau. (07.08.2023)
Top Pick

2023-08-09 10:22 UTC, zie1ony commented on newsletters/2023-08-09-newsletter.md
> +* [ZK Paris: Tarrance Van As - Applications of Zero Knowledge Primitives to Gaming](https://www.youtube.com/watch?v=b1F0W8Wy3kw) - lecture by Tarrance Van As. (04.08.2023)
Top Pick

2023-08-09 10:22 UTC, zie1ony commented on newsletters/2023-08-09-newsletter.md
> +* [Cośtam](https://twitter.com/0xSachinK/status/1687816562202292224). (05.08.2023)
Cośtam?

2023-08-09 10:37 UTC, kubaplas commented on newsletters/2023-08-09-newsletter.md
> +* [Honey, I Shrunk the Proof: Enabling on-chain verification for RISC Zero & Bonsai](https://www.risczero.com/news/on-chain-verification). (08.08.2023)
Awesome

2023-08-24 11:41 UTC, zie1ony approved these changes
Nice content :) Use top picks I've marked

2023-08-24 11:41 UTC, zie1ony commented on newsletters/2023-08-23-newsletter.md
> +* [The Cross-Domain Thesis Part 1: Setting The Stage](https://mirror.xyz/0x59567ea31347ba1430939E8a8aC58fDa014aBed9/e2pIdHzlaBi6m5GhsRGK0g5DyjgCVuU4lE614XmES5s) - article by Maven11 Research. (17.08.
Top Pick

2023-08-24 11:41 UTC, zie1ony commented on newsletters/2023-08-23-newsletter.md
> +* [How to code FRI from scratch](https://blog.lambdaclass.com/how-to-code-fri-from-scratch/) - tutorial by Not A Monad. (18.08.2023)
Top Pick

2023-08-24 11:41 UTC, zie1ony commented on newsletters/2023-08-23-newsletter.md
> +* [Batchman and Robin: Batched and Non-batched Branching for Interactive ZK](https://eprint.iacr.org/2023/1257.pdf) - academic text by Yibin Yang, David Heath, Carmit Hazay, Vladimir Kolesnikov and M
Top Pick

2023-08-24 11:41 UTC, zie1ony commented on newsletters/2023-08-23-newsletter.md
> +### Upcoming events
add https://zkwarsaw.dev/

2023-08-24 11:41 UTC, zie1ony commented on newsletters/2023-08-23-newsletter.md
> +* [Tree Types: Inside Aztec Labs](https://www.youtube.com/watch?v=ejZe98ZuiKU) - webinar by Sean Cheetham. (19.08.2023)
Same link as below?

2023-08-24 12:17 UTC, merged